### PR TITLE
(new PR) Fixes #813 - fixed missing links and thumbnail

### LINKED ISSUE #813: Missing links and images on Event Resources
- [x] links to Brand Palette
  - use https://party.webmaker.org/party-resources/MakerPartyBrandPalette.eps and https://party.webmaker.org/party-resources/MakerPartyBrandPalette.png ?
- [x] thumbnail(retina) for Poster Image
  - need file
- [x] "discussion forum" link in Ask The Community section
  - need link
- [x] "contact us" link in Request Support section
  - need link

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #813.

### CODE REVIEW

File: pages/event-resources.jsx [hunk 1]
```diff
@@ -193,8 +193,8 @@ var EventsResources = React.createClass({
           alt="Brand Palette Image"
           src1x="/img/event-resources-page/resource-thumbnails-03.png"
           src2x="/img/event-resources-page/resource-thumbnails-03@2x.png">
-            <LogoAssetLink href="">Download EPS</LogoAssetLink>
-            <LogoAssetLink href="">Download PNG</LogoAssetLink>
+            <LogoAssetLink href="https://party.webmaker.org/party-resources/MakerPartyBrandPalette.eps">Download EPS</LogoAssetLink>
+            <LogoAssetLink href="https://party.webmaker.org/party-resources/MakerPartyBrandPalette.png">Download PNG</LogoAssetLink>
```
Comment (mmmavis) [inline pages/event-resources.jsx]: points to party.webmaker.org for now (see https://github.com/mozilla/teach.webmaker.org/issues/828#issuecomment-97208662)
