### PR TITLE
Fixes #803 - removed alt for anchors + fixed a typo

### LINKED ISSUE #803: Correct missing and incorrect alt tags
if you hover over the "Clubs Toolkit" link on https://teach.mozilla.org/clubs/ the tooltip says "todo hover tooltip"

On "Event Resources" there is no existing alt tag.

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #803

### CODE REVIEW

File: pages/web-literacy.jsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ var ActivitiesPage = React.createClass({
                   <li>Using hyperlinks to access a range of resources on the web.</li>
                   <li>Reading, evaluating, and manipulating URLs.</li>
                   <li>Recognizing the common visual cues in the services.</li>
-                  <li>Exploring browser add-ons and extensions to provice additional functionality.</li>
+                  <li>Exploring browser add-ons and extensions to provide additional functionality.</li>
```
Comment (mmmavis) [inline pages/web-literacy.jsx]: I *think* we meant "provide" instead of "provice"?

Comment (toolness) [inline pages/web-literacy.jsx]: Sounds reasonable to me!
