### PR TITLE
Fix #110 - Add gulp webserver in watch task

### LINKED ISSUE #110: 'gulp watch' might as well start a server up
While we do currently support loading of the site via a `file:` URL, a bunch of stuff (like `pushState`) doesn't work on it, so we might as well have `gulp watch` start a dev server.

Not really sure which dev server is best here... There's [webpack-dev-server](http://webpack.github.io/docs/webpack-dev-server.html), which apparently gives us some webpack bonuses like auto-reload via socket.io, but I'm not sure if that will get triggered whenever we do something that's *not* webpack related.

Also worth looking into whatever [mofo-example-app](https://github.com/MozillaFoundation/mofo-example-app) uses.

@alicoding, are you interested in looking into this?

### PR DESCRIPTION
**Pull request by alicoding**
closes #110

### CODE REVIEW

**Comment by alicoding** [comment]
@toolness R?

File: gulpfile.js [hunk 1]
```diff
@@ -18,7 +19,8 @@ var BUILD_TASKS = [
   'copy-dirs',
   'less',
   'webpack',
-  'generate-index-files'
+  'generate-index-files',
+  'server'
```
Comment (toolness) [inline gulpfile.js]: oh, I don't think this is something we want in `BUILD_TASKS`... that array is only meant to hold all the tasks necessary to build the static site... I should probably add a comment or rename the constant to make that more obvious, sorry!

File: gulpfile.js [hunk 2]
```diff
@@ -129,6 +131,16 @@ gulp.task('watch', _.without(BUILD_TASKS, 'webpack'), function(cb) {
   gulp.watch(LESS_FILES, ['less']);
 });
 
+gulp.task('server', function () {
```
Comment (toolness) [inline gulpfile.js]: Hmm would it be better to just add this to the `watch` task? That way one could just run `gulp watch` in one Terminal window rather than having to run `gulp watch` in one, and then `gulp server` in another? Or is it possible to do `gulp watch server` and have both run simultaneously?

We should also add information about how to run/access this server to the quick start in the README. I can do that in a separate commit if you want, or you can do it, whatever your preference is.

**Comment by alicoding** [comment]
@toolness I updated a README file and would love to get you to look it before we merge this.

**Comment by toolness** [comment]
Cool!

Does gulp have to be globally installed? @gesa had contributed #101 so it wasn't needed, and I like anything that reduces setup time for devs... Also see this stackoverflow answer: http://stackoverflow.com/a/22115441

**Comment by alicoding** [comment]
@toolness done. Now we don't have to install gulp globally.

**Comment by toolness** [comment]
Hooray!!!! Thanks Ali!!!

**Comment by gesa** [comment]
Thanks guys, this is great!
